# Generated by Django 6.0 on 2026-01-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula'),
        ),
    ]
