# Generated by Django 5.2.4 on 2026-01-03 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Cuenta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('limit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite Mensual')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Actual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Categoría')),
                ('transaction_type', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso/Gasto')], max_length=20, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('client_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cliente / Tercero')),
                ('date', models.DateField(verbose_name='Fecha Movimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='contabilidad.account')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='products.order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.transactioncategory')),
            ],
        ),
    ]
