# Generated by Django 5.2.4 on 2026-01-04 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_provider_transaction_transfer_destination_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total')),
                ('description', models.TextField(verbose_name='Descripción / Concepto')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('partial', 'Pago Parcial'), ('paid', 'Pagada')], default='open', max_length=20, verbose_name='Estado')),
                ('date_created', models.DateField(verbose_name='Fecha de Creación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='contabilidad.provider', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Abonado')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contabilidad.debt', verbose_name='Deuda')),
            ],
        ),
    ]
