# Generated by Django 6.0 on 2026-01-30 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_invoice_invoiceitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True, verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='ShippingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('sender_name', models.CharField(max_length=100, verbose_name='Nombre Remitente')),
                ('sender_lastname', models.CharField(max_length=100, verbose_name='Apellido Remitente')),
                ('sender_cedula', models.CharField(blank=True, max_length=20, verbose_name='Cédula Remitente')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='Celular Remitente')),
                ('sender_department', models.CharField(max_length=100, verbose_name='Departamento Remitente')),
                ('sender_city', models.CharField(max_length=100, verbose_name='Ciudad Remitente')),
                ('sender_address', models.CharField(max_length=255, verbose_name='Dirección Remitente')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Nombre Destinatario')),
                ('recipient_lastname', models.CharField(max_length=100, verbose_name='Apellido Destinatario')),
                ('recipient_cedula', models.CharField(blank=True, max_length=20, verbose_name='Cédula Destinatario')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Celular Destinatario')),
                ('recipient_department', models.CharField(max_length=100, verbose_name='Departamento Destinatario')),
                ('recipient_city', models.CharField(max_length=100, verbose_name='Ciudad Destinatario')),
                ('recipient_address', models.CharField(max_length=255, verbose_name='Dirección Destinatario')),
                ('collection_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Valor a Recaudar')),
                ('observation', models.TextField(blank=True, verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_guides', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
