# Generated by Django 6.0 on 2026-01-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_shippingobservation_shippingguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingguide',
            name='recipient_department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento Destinatario'),
        ),
        migrations.AlterField(
            model_name='shippingguide',
            name='sender_department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento Remitente'),
        ),
    ]
