# Generated by Django 5.2.4 on 2026-02-06 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_alter_shippingguide_recipient_department_and_more'),
        ('products', '0015_populate_variant_dimensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='is_fixed_cost',
            field=models.BooleanField(default=False, help_text='Marcar si este gasto se incluye en el cálculo de overhead semanal', verbose_name='Es Gasto Fijo (Overhead)'),
        ),
        migrations.CreateModel(
            name='FinancialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('creado', 'Creado'), ('enviado', 'Enviado'), ('cobrado', 'Cobrado'), ('cancelado', 'Cancelado')], default='creado', max_length=20, verbose_name='Estado Financiero')),
                ('sale_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto de Venta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cobro')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('internal_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_status', to='products.internalorder')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_status', to='products.order')),
            ],
            options={
                'verbose_name': 'Estado Financiero',
                'verbose_name_plural': 'Estados Financieros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('week_number', models.PositiveIntegerField(verbose_name='Semana')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio (Lunes)')),
                ('end_date', models.DateField(verbose_name='Fecha Fin (Domingo)')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=10, verbose_name='Estado')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas Totales')),
                ('total_direct_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costos Directos')),
                ('total_fixed_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gastos Fijos')),
                ('overhead_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='% Overhead')),
                ('total_overhead_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Overhead Aplicado')),
                ('total_net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Utilidad Neta')),
                ('savings_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Ahorro')),
                ('distributable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Distribuible')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Pedidos Cobrados')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrada en')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semana Financiera',
                'verbose_name_plural': 'Semanas Financieras',
                'ordering': ['-year', '-week_number'],
                'unique_together': {('year', 'week_number')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='financial_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='contabilidad.financialweek'),
        ),
        migrations.CreateModel(
            name='JobCostingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='% Ahorro Empresa')),
                ('distribution_percentage', models.DecimalField(decimal_places=2, default=95.0, max_digits=5, verbose_name='% Distribución Socios')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenta_ahorro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.account', verbose_name='Cuenta Ahorro Empresa')),
                ('cuenta_costos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.account', verbose_name='Cuenta Reserva Costos')),
                ('cuenta_distribucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.account', verbose_name='Cuenta Distribución Socios')),
                ('cuenta_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.account', verbose_name='Cuenta Principal (Ingresos)')),
            ],
            options={
                'verbose_name': 'Configuración Job Costing',
                'verbose_name_plural': 'Configuración Job Costing',
            },
        ),
        migrations.CreateModel(
            name='OrderFinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Venta')),
                ('direct_costs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costos Directos')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Envío')),
                ('overhead_percentage', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='% Overhead')),
                ('overhead_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Overhead')),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Utilidad Neta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshot', to='contabilidad.financialstatus')),
                ('financial_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_snapshots', to='contabilidad.financialweek')),
            ],
            options={
                'verbose_name': 'Snapshot Financiero de Pedido',
                'verbose_name_plural': 'Snapshots Financieros de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('share_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje del monto distribuible (95%) que le corresponde', max_digits=5, verbose_name='% del Distributable')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario vinculado')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Asignado')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Bruto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado')], default='pending', max_length=10, verbose_name='Estado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagado en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='contabilidad.financialweek')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='contabilidad.partner')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.transaction')),
            ],
            options={
                'verbose_name': 'Distribución a Socio',
                'verbose_name_plural': 'Distribuciones a Socios',
                'unique_together': {('financial_week', 'partner')},
            },
        ),
    ]
