# Generated by Django 6.0 on 2025-12-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi-tag', help_text='Clase de icono Bootstrap (ej: bi-star)', max_length=50),
        ),
    ]
