# Generated by Django 5.2.4 on 2026-01-03 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_orderitem_shippingaddress_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Estado')),
                ('color', models.CharField(default='#6B2D7B', max_length=7, verbose_name='Color (Hex)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Por defecto al crear pedido')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.orderstatus'),
        ),
    ]
