# Generated by Django 5.2.4 on 2026-01-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orderstatus_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen cuadrada para el menú (PNG/JPG)', null=True, upload_to='categories/', verbose_name='Icono/Imagen'),
        ),
    ]
