# Generated by Django 5.2.4 on 2026-01-08 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_orderitem_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='Visible en Catálogo'),
        ),
        migrations.CreateModel(
            name='BulkUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('successful_uploads', models.IntegerField(default=0)),
                ('failed_uploads', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de Carga Masiva',
                'verbose_name_plural': 'Lotes de Carga Masiva',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkUploadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='bulk_upload_temp/')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando AI'), ('completed', 'Completado'), ('failed', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('ai_extracted_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.bulkuploadbatch')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'Item de Carga Masiva',
                'verbose_name_plural': 'Items de Carga Masiva',
                'ordering': ['-created_at'],
            },
        ),
    ]
