# Generated by Django 5.2.4 on 2026-01-08 18:09

from django.db import migrations


def migrate_categories_forward(apps, schema_editor):
    """Copiar categorías del campo ForeignKey al ManyToMany"""
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if product.category:
            product.categories.add(product.category)


def migrate_categories_backward(apps, schema_editor):
    """Restaurar primera categoría del ManyToMany al ForeignKey"""
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        first_category = product.categories.first()
        if first_category:
            product.category = first_category
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_categories_product_is_online_bulkuploadbatch_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_categories_forward, migrate_categories_backward),
    ]
