# Generated by Django 5.2.4 on 2026-01-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_migrate_category_to_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
