# Generated by Django 5.2.4 on 2026-01-15 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_old_category_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del pedido')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmado'), ('in_production', 'En Producción'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('total_items', models.IntegerField(default=0, verbose_name='Total de items')),
                ('total_estimated', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total estimado')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Pedido Interno',
                'verbose_name_plural': 'Pedidos Internos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalOrderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del grupo')),
                ('product_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de producto')),
                ('position', models.IntegerField(default=0, verbose_name='Posición')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Categoría')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='products.internalorder', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Grupo de Pedido',
                'verbose_name_plural': 'Grupos de Pedido',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='InternalOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('variant_details', models.CharField(max_length=300, verbose_name='Detalles de variante')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de agregado')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.internalorder', verbose_name='Pedido')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Item de Pedido Interno',
                'verbose_name_plural': 'Items de Pedido Interno',
                'ordering': ['created_at'],
            },
        ),
    ]
