# Generated by Django 5.2.4 on 2026-01-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_internalorder_internalordergroup_internalorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalorderitem',
            name='completed_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad completada'),
        ),
    ]
