# Generated by Django 5.2.4 on 2026-02-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_internalorderitem_completed_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si se desactiva, no aparecerá ni en catálogo ni en pedidos internos.', verbose_name='Producto Activo (General)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='Visible en Catálogo Público'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('vinilo_corte', 'Vinilo de Corte'), ('impreso_globo', 'Impreso para Globos'), ('cinta', 'Cinta Ramos'), ('logo', 'Stickers Logo'), ('interno', 'Manejo Interno / Otros')], default='vinilo_corte', max_length=20),
        ),
    ]
