# Generated by Django 5.2.4 on 2026-02-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_is_active_alter_product_is_online_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('unit', models.CharField(choices=[('unidad', 'Por Unidad'), ('metro_lineal', 'Metro Lineal'), ('metro_cuadrado', 'Metro Cuadrado'), ('fijo', 'Costo Fijo')], default='unidad', max_length=30, verbose_name='Unidad de medida')),
                ('default_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por defecto por unidad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Costo',
                'verbose_name_plural': 'Tipos de Costo',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='internalorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Alto (cm)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ancho (cm)'),
        ),
        migrations.CreateModel(
            name='OrderCostBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de producto')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('calculated_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Cantidad calculada')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Ingresado manualmente')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.costtype', verbose_name='Tipo de costo')),
                ('internal_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdowns', to='products.internalorder')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdowns', to='products.order')),
            ],
            options={
                'verbose_name': 'Desglose de Costo',
                'verbose_name_plural': 'Desgloses de Costos',
                'ordering': ['product_type', 'cost_type__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTypeCostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50, verbose_name='Tipo de producto')),
                ('calculation_method', models.CharField(choices=[('per_unit', 'Por unidad (cantidad × precio)'), ('linear_meters', 'Metros lineales (layout en material)'), ('square_meters', 'Metros cuadrados (alto × ancho)'), ('manual', 'Manual (ingresado por admin)')], default='per_unit', max_length=30, verbose_name='Método de cálculo')),
                ('material_width_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Ancho del rollo/material para cálculos de metros lineales', max_digits=6, null=True, verbose_name='Ancho del material (cm)')),
                ('position', models.IntegerField(default=0, verbose_name='Orden de display')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.costtype', verbose_name='Tipo de costo')),
            ],
            options={
                'verbose_name': 'Config. Costo por Tipo de Producto',
                'verbose_name_plural': 'Config. Costos por Tipo de Producto',
                'ordering': ['product_type', 'position'],
                'unique_together': {('product_type', 'cost_type')},
            },
        ),
    ]
