# Generated by Django 5.2.4 on 2026-02-06 18:22

import re
from decimal import Decimal
from django.db import migrations


def populate_dimensions(apps, schema_editor):
    """Extract dimensions from Size.dimensions field and populate variant height_cm/width_cm"""
    ProductVariant = apps.get_model('products', 'ProductVariant')

    for variant in ProductVariant.objects.select_related('size').all():
        if not variant.size or not variant.size.dimensions:
            continue

        dims = variant.size.dimensions
        # Parse patterns like "19x25cm", "14,5x14,3cm", "19x15cm"
        match = re.match(r'([\d]+[,.]?\d*)\s*x\s*([\d]+[,.]?\d*)\s*cm', dims, re.IGNORECASE)
        if match:
            width_str = match.group(1).replace(',', '.')
            height_str = match.group(2).replace(',', '.')
            variant.width_cm = Decimal(width_str)
            variant.height_cm = Decimal(height_str)
            variant.save(update_fields=['width_cm', 'height_cm'])


def reverse_populate(apps, schema_editor):
    """Reverse: clear dimension fields"""
    ProductVariant = apps.get_model('products', 'ProductVariant')
    ProductVariant.objects.update(width_cm=None, height_cm=None)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_add_costs_system'),
    ]

    operations = [
        migrations.RunPython(populate_dimensions, reverse_populate),
    ]
