# Generated by Django 5.2.4 on 2026-02-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_populate_variant_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtype',
            name='special_material_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio para materiales marcados como especiales (ej: Metalizado, Mailan)', max_digits=10, verbose_name='Precio material especial (Metalizado)'),
        ),
    ]
