# Generated by Django 5.2.4 on 2026-02-10

import django.db.models.deletion
from django.db import migrations, models


def delete_legacy_automatic_costs(apps, schema_editor):
    OrderCostBreakdown = apps.get_model("products", "OrderCostBreakdown")
    OrderCostBreakdown.objects.filter(is_manual=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0008_transactioncategory_is_fixed_cost_financialstatus_and_more"),
        ("products", "0017_internalorder_discount_amount_order_discount_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="costtype",
            name="accounting_category",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"transaction_type": "egreso"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_types",
                to="contabilidad.transactioncategory",
                verbose_name="Categoria contable por defecto",
            ),
        ),
        migrations.AddField(
            model_name="ordercostbreakdown",
            name="accounting_category",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"transaction_type": "egreso"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_cost_breakdowns",
                to="contabilidad.transactioncategory",
                verbose_name="Categoria contable",
            ),
        ),
        migrations.AddField(
            model_name="ordercostbreakdown",
            name="accounting_posted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de registro contable"),
        ),
        migrations.AddField(
            model_name="ordercostbreakdown",
            name="accounting_status",
            field=models.CharField(
                choices=[("pending", "Pendiente"), ("posted", "Registrado en contabilidad")],
                default="pending",
                max_length=20,
                verbose_name="Estado contable",
            ),
        ),
        migrations.AddField(
            model_name="ordercostbreakdown",
            name="accounting_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_cost_breakdown",
                to="contabilidad.transaction",
                verbose_name="Movimiento contable",
            ),
        ),
        migrations.RunPython(delete_legacy_automatic_costs, migrations.RunPython.noop),
    ]
