# Generated by Django 5.2.4 on 2026-02-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_manual_order_costs_accounting_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalorder',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento sobre el total (0-100)', max_digits=5, verbose_name='Porcentaje de descuento'),
        ),
        migrations.AddField(
            model_name='ordercostbreakdown',
            name='cost_category',
            field=models.CharField(choices=[('production', 'Producción'), ('discount', 'Descuento'), ('shipping', 'Envío'), ('other', 'Otro')], default='production', max_length=20, verbose_name='Categoría de costo'),
        ),
        migrations.AddField(
            model_name='ordercostbreakdown',
            name='is_system_generated',
            field=models.BooleanField(default=False, help_text='Indica si fue creado automáticamente (descuento/envío)', verbose_name='Generado automáticamente'),
        ),
    ]
